# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/hengfengli/test-circleci

    steps:
      - checkout
      - run: go test -v ./...

  integration_tests:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/hengfengli/test-circleci

    steps:
      - checkout
      - run: go test -v integration_test.go

workflows:
  version: 2

  build:
    jobs:
      - unit_tests
      - integration_tests:
        filters:
          branches:
            # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
            ignore: /pull\/[0-9]+/

